let
    proj=mgis[proj], ops=mgis[gisLayerQueryOperators],
    wgs=proj[fromEPSG][#"EPSG:4326"], web=proj[fromEPSG][#"EPSG:3857"],
    xy=mgis[gisLayerCreateFromTableWithXY], join=mgis[gisLayerJoinSpatial],
    close=(a,b,t)=>Number.Abs(a-b)<=t,
    distances=List.Transform(projectionReferences[distances],(ref)=>
        close(proj[distance](ref[first],ref[second],wgs),ref[expected],0.001)),
    origin=xy(#table({"ID","X","Y"},{{"Origin",0,0}}),"X","Y",wgs),
    metres=xy(#table({"ID","X","Y"},{{"Near",100,0},{"Far",1000,0}}),"X","Y",web),
    mixed=join(origin,metres,ops[gisNearest],"Left Outer",[analysisCRS=web]),
    reverse=join(metres,origin,ops[gisNearest],"Inner",[analysisCRS=web]),
    // Cross the date line: degree-space/planar pruning would prefer "Wrong".
    dateSource=xy(#table({"X","Y"},{{179.9,10}}),"X","Y",wgs),
    dateTargets=xy(#table({"ID","X","Y"},{{"Correct",-179.9,10},{"Wrong",179,10},{"Far",0,0}}),"X","Y",wgs),
    geodesic=join(dateSource,dateTargets,ops[gisNearest],"Inner"),
    explicitGeo=join(dateSource,dateTargets,ops[gisNearestGeodesicN](2),"Inner"),
    projectedDates=mgis[gisLayerReproject](dateTargets,web),
    mixedGeo=join(dateSource,projectedDates,ops[gisNearest],"Inner",[mode="Geodesic"]),
    query=mgis[gisLayerQuerySpatial](metres,mgis[gisShapeCreateFromWKT]("POINT(0 0)"),ops[gisNearest],wgs,[analysisCRS=web]),
    queriedGeo=mgis[gisLayerQuerySpatial](dateTargets,mgis[gisShapeCreateFromWKT]("POINT(179.9 10)"),ops[gisNearest]),
    unknown=xy(#table({"X","Y"},{{0,0}}),"X","Y"),
    empty=mgis[gisLayerCreateBlank]("shape",10,web),
    noMatches=join(origin,empty,ops[gisNearest],"Inner",[analysisCRS=web]),
    outer=join(origin,empty,ops[gisNearest],"Full Outer",[analysisCRS=web]),
    filtered=mgis[gisLayerQueryRelational](metres,each [ID]="Far"),
    filteredNearest=join(origin,filtered,ops[gisNearest],"Inner",[analysisCRS=web]),
    feet=proj[fromProj4]("+proj=merc +datum=WGS84 +units=ft"),
    footSources=xy(#table({"X","Y"},{{0,0}}),"X","Y",feet),
    footTargets=xy(#table({"ID","X","Y"},{{"A",100,0},{"B",99,0}}),"X","Y",feet),
    footJoin=join(footSources,footTargets,ops[gisNearest],"Inner"),
    allGeometries=mgis[gisLayerCreateFromTableWithWKT](#table({"ID","geom"},{
        {1,"POINT(1 2)"},{2,"LINESTRING(1 2,3 4)"},{3,"POLYGON((1 2,3 2,3 4,1 2))"},
        {4,"MULTIPOINT((1 2),(3 4))"},{5,"MULTILINESTRING((1 2,3 4),(5 6,7 8))"},
        {6,"MULTIPOLYGON(((1 2,3 2,3 4,1 2)))"},
        {7,"GEOMETRYCOLLECTION(POINT(1 2),LINESTRING(3 4,5 6))"}
    }),"geom",wgs),
    projected=mgis[gisLayerReproject](allGeometries,web),
    returned=mgis[gisLayerReproject](projected,wgs),
    rightCustom=join(origin,projected,ops[gisNearest],"Right Outer",[analysisCRS=web]),
    fullCustom=join(origin,projected,ops[gisNearest],"Full Outer",[analysisCRS=web]),
    jsonLayer=mgis[gisLayerCreateFromTableWithGeoJSON](#table({"ID","geom"},{{1,"{""type"":""Point"",""coordinates"":[1,2]}"}}),"geom"),
    collection=mgis[gisShapeCreateFromGeoJSON]("{""type"":""GeometryCollection"",""geometries"":[{""type"":""Point"",""coordinates"":[1,2]},{""type"":""LineString"",""coordinates"":[[3,4],[5,6]]}]}"),
    customDatum=proj[withDatumTransform](proj[fromProj4]("+proj=longlat +ellps=airy +nadgrids=custom.tif"),each _,each _),
    inserted=mgis[gisLayerInsertRows](metres,{[ID="Inserted",X=1,Y=0,shape=mgis[gisShapeCreateFromWKT]("POINT(1 0)")]}),
    insertedNearest=join(origin,inserted,ops[gisNearest],"Inner",[analysisCRS=web]),
    right=join(origin,empty,ops[gisNearest],"Right Outer",[analysisCRS=web]),
    checks=[
        IndependentGeodesics=List.AllTrue(distances),
        MixedNearest=mixed[table]{0}[layer2][ID]="Near" and close(mixed[table]{0}[dist],100,0.000001),
        AnalysisCRS=mixed[TProjection]=web and geodesic[TProjection]=wgs,
        OriginalRecords=mixed[table]{0}[layer1][shape]=origin[table]{0}[shape],
        ReverseJoin=Table.RowCount(reverse[table])=2 and List.AllTrue(List.Transform(Table.Column(reverse[table],"dist"),each List.Contains({100,1000},_))),
        DateLineNeighbour=geodesic[table]{0}[layer2][ID]="Correct" and close(geodesic[table]{0}[dist],21927.87247793737,0.001),
        ExplicitGeodesicN=Table.RowCount(explicitGeo[table])=2 and List.Contains(Table.Column(Table.ExpandRecordColumn(explicitGeo[table],"layer2",{"ID"}),"ID"),"Correct"),
        MixedGeodesic=mixedGeo[table]{0}[layer2][ID]="Correct" and close(mixedGeo[table]{0}[dist],21927.87247793737,0.001),
        QueryDistances=query[table]{0}[ID]="Near" and close(query[table]{0}[dist],100,0.000001) and query[TProjection]=web,
        QueryGeodesic=queriedGeo[table]{0}[ID]="Correct" and queriedGeo[TProjection]=wgs,
        MixedUnknownRejected=(try Table.RowCount(join(origin,unknown,ops[gisNearest],"Inner")[table]))[HasError],
        GeographicPlanarRejected=(try Table.RowCount(join(origin,origin,ops[gisNearest],"Inner",[mode="Planar"])[table]))[HasError],
        EmptyJoin=Table.RowCount(noMatches[table])=0 and Table.HasColumns(noMatches[table],{"shape","layer1","layer2","dist"}),
        OuterJoin=Table.RowCount(outer[table])=1 and outer[table]{0}[layer2]=null and outer[table]{0}[shape][Envelope][MinX]=0,
        FilteringKeepsCRS=filtered[TProjection]=web and filteredNearest[table]{0}[layer2][ID]="Far" and close(filteredNearest[table]{0}[dist],1000,0.000001),
        InsertionKeepsCRS=inserted[TProjection]=web and insertedNearest[table]{0}[layer2][ID]="Inserted" and close(insertedNearest[table]{0}[dist],1,0.000001),
        RightOuterEmpty=Table.RowCount(right[table])=0,
        CustomGeometryOuterJoins=Table.RowCount(rightCustom[table])=7 and Table.RowCount(fullCustom[table])=7,
        FeetDistances=close(footJoin[table]{0}[dist],99*0.3048,0.000001) and footJoin[table]{0}[layer2][ID]="B",
        PlanarDistance=close(proj[distance]({0,0},{100,0},feet,[mode="Planar"]),30.48,0.000001),
        GeometryKinds=Table.Column(projected[table],"ID")={1,2,3,4,5,6,7} and List.AllTrue(List.Transform(Table.ToRecords(returned[table]),each
            close(_[geom][Envelope][MinX],allGeometries[table]{_[ID]-1}[geom][Envelope][MinX],1e-8) and
            close(_[geom][Envelope][MaxY],allGeometries[table]{_[ID]-1}[geom][Envelope][MaxY],1e-8))),
        IndexRebuilt=List.AllTrue(List.Transform(mgis[gisLayerQuerySpatial](projected,projected[table]{0}[geom],ops[gisIntersects])[table][ID],each List.Contains({1,2,3,4,5,6,7},_))),
        GeoJSON=jsonLayer[TProjection]=wgs and jsonLayer[table]{0}[geom][Geometry][X]=1 and collection[Kind]="GEOMETRYCOLLECTION",
        EmptyGeoJSONRejected=(try mgis[gisShapeCreateFromGeoJSON]("{""type"":""LineString"",""coordinates"":[]}")[Envelope])[HasError],
        CustomDatum=proj[transform]({1,2},customDatum,wgs)={1,2},
        NearAntipodalFailsClearly=(try proj[distance]({0,0},{179.7,0.1},wgs))[HasError],
        NonPointGeodesicRejected=(try Table.RowCount(join(origin,allGeometries,ops[gisNearestGeodesicN](7),"Inner")[table]))[HasError],
        UndeclaredReprojectionRejected=(try Table.RowCount(mgis[gisLayerReproject](unknown,web)[table]))[HasError]
    ],
    evaluated=Record.FromList(List.Transform(Record.FieldNames(checks),(name)=>
        let result=try Record.Field(checks,name) in if result[HasError] then result[Error][Message] else result[Value]),Record.FieldNames(checks))
in if List.AllTrue(List.Transform(Record.FieldValues(evaluated),each _=true)) then evaluated
    else error Error.Record("TestFailure",Text.FromBinary(Json.FromValue(evaluated)),null)
